### PR TITLE
sync images from memos to logseq

### PR DESCRIPTION
**Pull request by zhaochunqi**
This pr adds support for images .

### CODE REVIEW

**Comment by zhaochunqi** [comment]
This would close https://github.com/EINDEX/logseq-memos-sync/issues/6

**Comment by EINDEX** [comment]
Hi, 

Thanks for making PR here, your code is petty nice.

But I found some cases below.

- if the resource did not have `externalLink`, still generate an image link with an empty link. We can create a filter that just shows up with an image that has `externalLink`.  And I just found a workaround that can show the resource via internal link, the internal link will be `https://memos.xllb.cc:8443/o/r/<resource-id>?openId=<your-openId-here>`. I found this logic here https://github.com/usememos/memos/blob/28203bbaf9583539f4ed70e486fac10b275b77d6/api/v1/rss.go#L117.

- if this is not an image resource, we can show it as a normal link to the resource. or not ignore it? this pr only about image sync, so I suggest we ignore the other types.
 
Anyway Thanks for your PR.

**Comment by zhaochunqi** [comment]
You're correct, I should have considered images without an external link.

If it's not an image resource, I believe the syntax in Logseq remains the same: `name`. 

I'll attempt to rectify the external link issue as soon as possible.
Thank you for your review!

**Comment by zhaochunqi** [comment]
Hi, @EINDEX. I've pushed the code that supports images without external links. I've tested it with my local setup using different memo visibilities.

The code structure might not be as you desired, feel free to modify it as I will certainly learn a lot from that.

**Comment by EINDEX** [comment]
LGTM, Thanks for the PR.

**Pull request merged**
